Add cleanup 1
aichner/React-MDB-Template pull request #26
Opened 2019-09-11 12:44 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- The code quality including spaces could be better. #24 
- There is a `scrollToTop` function which is not being used. #25 

**What is the new behavior (if this is a feature change)?**
- The code quality has been improved. #24 
- The `scrollToTop` function has been removed. #25

2019-09-11 12:44 UTC, Aichnerc reviewed
Looks okay to me.

2019-09-12 06:34 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2019-09-12 06:34 UTC, kleberbaum commented on package.json
> +  "version": "1.0.2",
This update isn't mentioned in the PR.

2019-09-12 08:09 UTC, Aichnerc commented on package.json
> +  "version": "1.0.2",
Done

2019-09-13 21:01 UTC, kleberbaum approved these changes
Should be ok to merge.

2019-09-13 21:01 UTC, merged